name: Build and upload
on: [workflow_dispatch, push, pull_request]

jobs:
  main:
    name: Build
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          cd ${{ GITHUB.WORKSPACE }}
          chmod 755 build.sh
          ./build.sh

        
